#!/bin/bash

set -e


function status {
  echo
  echo -e "\033[94m[test] $1\033[0m"
}

# Delete the working directory when the script exits.
function cleanup {
  if [[ -n "$nocleanup" ]]; then
    echo
    echo "Test directory: $working"
  else
    rm -rf "$working"
  fi
}

# Parse command-line arguments.
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    --no-cleanup)
      nocleanup=true
      shift
      ;;
    -h|--help)
      echo "Run the test suite."
      echo
      echo "Flags"
      echo "  --no-cleanup    Don't remove the test directory when finished."
      echo "  -h, --help      Display this help message and exit."
      exit 0
      ;;
    *)
      echo "Unknown argument: $key"
      exit 1
      ;;
  esac
done


d=$(realpath $(dirname $0))
working=$(mktemp -d)
if [[ ! -d "$working" ]]; then
  echo "Error: unable to create temporary directory with mktemp."
  exit 1
fi

trap cleanup EXIT

if [[ ! -d "test_repo/.venv" ]]; then
  echo "Error: no virtual environment found in test_repo/.venv"
  echo "Create one with 'virtualenv --python=python3 test_repo/.venv'"
  exit 1
fi

cp -r test_repo "$working"
cd "$working/test_repo"

status "Initializing git repository."
git init
git add bad_python_format.py to_be_removed.txt includes_todo.txt
git commit -m "Initial commit"

status "Installing development version of iprecommit."
source .venv/bin/activate
pip3 install "$d"

status "Running tests"
iprecommit install

# Modify files so that they are checked.
echo -e "\n\n" >> bad_python_format.py
echo -e "\n\n" >> includes_todo.txt
git add bad_python_format.py includes_todo.txt

# Remove a file (regression test for #23).
rm to_be_removed.txt
git add to_be_removed.txt

export NO_COLOR=true
export IPRECOMMIT_FANCY_OUTPUT=0

echo "Checking output of 'iprecommit run --staged'"
iprecommit run --staged &> precommit_output || true
git diff --no-index ref/precommit_output precommit_output

echo "Checking output of 'git commit'"
git commit -m "Test commit" &> git_precommit_output || true
git diff --no-index ref/precommit_output git_precommit_output

echo "Checking output of 'iprecommit fix --staged'"
iprecommit fix --staged &> precommit_fix_output || true
git diff --no-index ref/precommit_fix_output precommit_fix_output
git diff --no-index ref/fixed_python_format.py bad_python_format.py

# Modify bad_python_format.py to have bad format again.
git reset HEAD bad_python_format.py > /dev/null
git checkout -- bad_python_format.py
# Unstaged change to bad_python_format.py so that iprecommit picks up on it.
echo -e "\n\n" >> bad_python_format.py

echo "Checking output of 'iprecommit run'"
iprecommit run &> precommit_output || true
git diff --no-index ref/precommit_working_output precommit_output

echo "Checking output of 'iprecommit fix'"
iprecommit fix &> precommit_fix_output || true
git diff --no-index ref/precommit_fix_working_output precommit_fix_output
git diff --no-index ref/fixed_python_format.py bad_python_format.py

echo
echo -e "\033[92mTests passed!\033[0m"
