autofix = true

[[pre_commit]]
name = "NoForbiddenStrings"
cmd = ["iprecommit-no-forbidden-strings", "--paths"]

[[pre_commit]]
name = "NewlineAtEndOfFile"
cmd = ["iprecommit-newline-at-eof"]

[[pre_commit]]
name = "CommitMessageTypos"
cmd = ["iprecommit-typos", "--paths"]

[[pre_commit]]
name = "PythonFormat"
cmd = ["black", "--check"]
filters = ["*.py"]
fix_cmd = ["black"]

# TODO: should consider deleted files
[[pre_commit]]
name = "PythonTypes"
cmd = [".venv/bin/mypy", "iprecommit"]
pass_files = false
filters = ["*.py"]

[[pre_commit]]
name = "PythonLint"
cmd = [".venv/bin/flake8", "iprecommit"]
pass_files = false
filters = ["*.py"]

# TODO: should consider deleted files
[[pre_commit]]
name = "ProjectTests"
cmd = [".venv/bin/pytest", "--tb=short"]
pass_files = false
filters = ["*.py"]

[[commit_msg]]
name = "CommitMessageFormat"
cmd = ["iprecommit-commit-msg-format"]

[[commit_msg]]
name = "CommitMessageTypos"
cmd = ["iprecommit-typos", "--paths"]

[[pre_push]]
cmd = ["iprecommit-no-forbidden-strings", "--strings", "DO NOT PUSH", "--commits"]
